In [1]:
import numpy as np

In [2]:
l1 =[1,2,3]
a = np.asarray(l1)
a

array([1, 2, 3])

In [3]:
 type(a)

numpy.ndarray

In [4]:
matrix = [[1,2,3],[5,6,7]]
np.array(matrix)

array([[1, 2, 3],
       [5, 6, 7]])

In [9]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.linspace(0,20,3)

array([ 0., 10., 20.])

## Random 

In [23]:

np.random.rand(2,3) #bw 0 and 1

array([[0.46411182, 0.60325189, 0.15267519],
       [0.19893529, 0.86532459, 0.33810595]])

In [26]:
np.random.randn(5,4)

array([[ 0.88003701,  0.90958806,  1.42745707,  0.37432662],
       [-0.68234626, -1.47320953,  0.01301168, -0.65253972],
       [ 0.97825421, -0.09040006,  2.40581426,  1.78689426],
       [-0.19799223, -0.71889968,  0.20147755, -0.22947642],
       [-1.74855334,  1.03729456,  0.23176322, -0.07149961]])

In [28]:
np.random.randint(1,100,(2,2))

array([[31, 19],
       [96, 29]])

In [45]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

## Shape

In [46]:
arr.shape

(25,)

In [41]:
ranarr

array([15, 27, 10, 16,  7, 35, 27, 14, 45, 29])

In [48]:
arr.reshape(1,25).shape
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
arr.shape

(25,)

In [51]:
arr.dtype

dtype('int64')

In [53]:
ranarr

array([47, 37, 36, 14,  0, 11, 30, 13, 46, 21])

In [54]:
ranarr.max()

47

In [55]:
ranarr.argmax()

0

## Arithmetic

In [58]:
arr  = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [60]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [61]:
arr/arr

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [62]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [63]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [64]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

## Indexing and selection

In [66]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
arr[8]

8

In [68]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Broadcasting

In [70]:
arr[:4] = 100
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9])

### Copying

In [77]:
part = arr[3:7]
part

array([100,   4,   5,   6])

In [78]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9])

In [79]:
part[:] = 555

In [80]:
part

array([555, 555, 555, 555])

In [81]:
arr

array([100, 100, 100, 555, 555, 555, 555,   7,   8,   9])

Orignal array also gets changed bec part was ptr to orig arr

In [83]:
arr_copy = arr[3:7].copy()
arr_copy

array([555, 555, 555, 555])

In [84]:
arr_copy[:] = 666
arr_copy

array([666, 666, 666, 666])

In [85]:
arr

array([100, 100, 100, 555, 555, 555, 555,   7,   8,   9])

In [89]:
mat = np.arange(15).reshape(3,5)
mat

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [91]:
mat[0][3]

3

In [94]:
mat[1:,2:4]

array([[ 7,  8],
       [12, 13]])

In [95]:
mat[1:,:2]

array([[ 5,  6],
       [10, 11]])

## Conditional Selection

In [97]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
arr >4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [98]:
arr[arr>4]

array([5, 6, 7, 8, 9])

In [104]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [106]:
a.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [107]:
a.sum(axis = 1)

array([ 10,  35,  60,  85, 110])

In [108]:
a.argmax()

24